/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTriagemRouteImport } from './routes/_authenticated/triagem'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedIaInsightsRouteImport } from './routes/_authenticated/ia-insights'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPeticoesIndexRouteImport } from './routes/_authenticated/peticoes/index'
import { Route as AuthenticatedSettingsOcrRouteImport } from './routes/_authenticated/settings/ocr'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsEventCategoriesRouteImport } from './routes/_authenticated/settings/event-categories'
import { Route as AuthenticatedSettingsDocumentsRouteImport } from './routes/_authenticated/settings/documents'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings/company'
import { Route as AuthenticatedCrmServicesRouteImport } from './routes/_authenticated/crm/services'
import { Route as AuthenticatedCrmOportunidadesArquivadasRouteImport } from './routes/_authenticated/crm/oportunidades-arquivadas'
import { Route as AuthenticatedCrmOportunidadesRouteImport } from './routes/_authenticated/crm/oportunidades'
import { Route as AuthenticatedCrmEtapasFunilRouteImport } from './routes/_authenticated/crm/etapas-funil'
import { Route as AuthenticatedCrmDashboardRouteImport } from './routes/_authenticated/crm/dashboard'
import { Route as AuthenticatedCrmContatosRouteImport } from './routes/_authenticated/crm/contatos'
import { Route as AuthenticatedCrmCamposOportunidadeRouteImport } from './routes/_authenticated/crm/campos-oportunidade'
import { Route as AuthenticatedCrmCalendarioRouteImport } from './routes/_authenticated/crm/calendario'
import { Route as AuthenticatedContatosIdRouteImport } from './routes/_authenticated/contatos/$id'
import { Route as AuthenticatedCalcWizardRouteImport } from './routes/_authenticated/calc/wizard'
import { Route as AuthenticatedCalcSelecaoRouteImport } from './routes/_authenticated/calc/selecao'
import { Route as AuthenticatedCalcResultsRouteImport } from './routes/_authenticated/calc/results'
import { Route as AuthenticatedCalcListaRouteImport } from './routes/_authenticated/calc/lista'
import { Route as AuthenticatedPeticoesEditorIdRouteImport } from './routes/_authenticated/peticoes/editor.$id'
import { Route as AuthenticatedCrmOportunidadeIdRouteImport } from './routes/_authenticated/crm/oportunidade.$id'
import { Route as AuthenticatedCrmEtapaIdRouteImport } from './routes/_authenticated/crm/etapa.$id'
import { Route as AuthenticatedCalcRelatorioIdRouteImport } from './routes/_authenticated/calc/relatorio.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTriagemRoute = AuthenticatedTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIaInsightsRoute = AuthenticatedIaInsightsRouteImport.update({
  id: '/ia-insights',
  path: '/ia-insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeticoesIndexRoute =
  AuthenticatedPeticoesIndexRouteImport.update({
    id: '/peticoes/',
    path: '/peticoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsOcrRoute =
  AuthenticatedSettingsOcrRouteImport.update({
    id: '/settings/ocr',
    path: '/settings/ocr',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsEventCategoriesRoute =
  AuthenticatedSettingsEventCategoriesRouteImport.update({
    id: '/settings/event-categories',
    path: '/settings/event-categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDocumentsRoute =
  AuthenticatedSettingsDocumentsRouteImport.update({
    id: '/settings/documents',
    path: '/settings/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmServicesRoute =
  AuthenticatedCrmServicesRouteImport.update({
    id: '/crm/services',
    path: '/crm/services',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmOportunidadesArquivadasRoute =
  AuthenticatedCrmOportunidadesArquivadasRouteImport.update({
    id: '/crm/oportunidades-arquivadas',
    path: '/crm/oportunidades-arquivadas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmOportunidadesRoute =
  AuthenticatedCrmOportunidadesRouteImport.update({
    id: '/crm/oportunidades',
    path: '/crm/oportunidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmEtapasFunilRoute =
  AuthenticatedCrmEtapasFunilRouteImport.update({
    id: '/crm/etapas-funil',
    path: '/crm/etapas-funil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmDashboardRoute =
  AuthenticatedCrmDashboardRouteImport.update({
    id: '/crm/dashboard',
    path: '/crm/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmContatosRoute =
  AuthenticatedCrmContatosRouteImport.update({
    id: '/crm/contatos',
    path: '/crm/contatos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmCamposOportunidadeRoute =
  AuthenticatedCrmCamposOportunidadeRouteImport.update({
    id: '/crm/campos-oportunidade',
    path: '/crm/campos-oportunidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmCalendarioRoute =
  AuthenticatedCrmCalendarioRouteImport.update({
    id: '/crm/calendario',
    path: '/crm/calendario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContatosIdRoute = AuthenticatedContatosIdRouteImport.update({
  id: '/contatos/$id',
  path: '/contatos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalcWizardRoute = AuthenticatedCalcWizardRouteImport.update({
  id: '/calc/wizard',
  path: '/calc/wizard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalcSelecaoRoute =
  AuthenticatedCalcSelecaoRouteImport.update({
    id: '/calc/selecao',
    path: '/calc/selecao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalcResultsRoute =
  AuthenticatedCalcResultsRouteImport.update({
    id: '/calc/results',
    path: '/calc/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalcListaRoute = AuthenticatedCalcListaRouteImport.update({
  id: '/calc/lista',
  path: '/calc/lista',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeticoesEditorIdRoute =
  AuthenticatedPeticoesEditorIdRouteImport.update({
    id: '/peticoes/editor/$id',
    path: '/peticoes/editor/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmOportunidadeIdRoute =
  AuthenticatedCrmOportunidadeIdRouteImport.update({
    id: '/crm/oportunidade/$id',
    path: '/crm/oportunidade/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmEtapaIdRoute = AuthenticatedCrmEtapaIdRouteImport.update({
  id: '/crm/etapa/$id',
  path: '/crm/etapa/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalcRelatorioIdRoute =
  AuthenticatedCalcRelatorioIdRouteImport.update({
    id: '/calc/relatorio/$id',
    path: '/calc/relatorio/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ia-insights': typeof AuthenticatedIaInsightsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/calc/lista': typeof AuthenticatedCalcListaRoute
  '/calc/results': typeof AuthenticatedCalcResultsRoute
  '/calc/selecao': typeof AuthenticatedCalcSelecaoRoute
  '/calc/wizard': typeof AuthenticatedCalcWizardRoute
  '/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/crm/calendario': typeof AuthenticatedCrmCalendarioRoute
  '/crm/campos-oportunidade': typeof AuthenticatedCrmCamposOportunidadeRoute
  '/crm/contatos': typeof AuthenticatedCrmContatosRoute
  '/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/crm/etapas-funil': typeof AuthenticatedCrmEtapasFunilRoute
  '/crm/oportunidades': typeof AuthenticatedCrmOportunidadesRoute
  '/crm/oportunidades-arquivadas': typeof AuthenticatedCrmOportunidadesArquivadasRoute
  '/crm/services': typeof AuthenticatedCrmServicesRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/documents': typeof AuthenticatedSettingsDocumentsRoute
  '/settings/event-categories': typeof AuthenticatedSettingsEventCategoriesRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/ocr': typeof AuthenticatedSettingsOcrRoute
  '/peticoes': typeof AuthenticatedPeticoesIndexRoute
  '/calc/relatorio/$id': typeof AuthenticatedCalcRelatorioIdRoute
  '/crm/etapa/$id': typeof AuthenticatedCrmEtapaIdRoute
  '/crm/oportunidade/$id': typeof AuthenticatedCrmOportunidadeIdRoute
  '/peticoes/editor/$id': typeof AuthenticatedPeticoesEditorIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ia-insights': typeof AuthenticatedIaInsightsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/calc/lista': typeof AuthenticatedCalcListaRoute
  '/calc/results': typeof AuthenticatedCalcResultsRoute
  '/calc/selecao': typeof AuthenticatedCalcSelecaoRoute
  '/calc/wizard': typeof AuthenticatedCalcWizardRoute
  '/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/crm/calendario': typeof AuthenticatedCrmCalendarioRoute
  '/crm/campos-oportunidade': typeof AuthenticatedCrmCamposOportunidadeRoute
  '/crm/contatos': typeof AuthenticatedCrmContatosRoute
  '/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/crm/etapas-funil': typeof AuthenticatedCrmEtapasFunilRoute
  '/crm/oportunidades': typeof AuthenticatedCrmOportunidadesRoute
  '/crm/oportunidades-arquivadas': typeof AuthenticatedCrmOportunidadesArquivadasRoute
  '/crm/services': typeof AuthenticatedCrmServicesRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/documents': typeof AuthenticatedSettingsDocumentsRoute
  '/settings/event-categories': typeof AuthenticatedSettingsEventCategoriesRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/ocr': typeof AuthenticatedSettingsOcrRoute
  '/peticoes': typeof AuthenticatedPeticoesIndexRoute
  '/calc/relatorio/$id': typeof AuthenticatedCalcRelatorioIdRoute
  '/crm/etapa/$id': typeof AuthenticatedCrmEtapaIdRoute
  '/crm/oportunidade/$id': typeof AuthenticatedCrmOportunidadeIdRoute
  '/peticoes/editor/$id': typeof AuthenticatedPeticoesEditorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ia-insights': typeof AuthenticatedIaInsightsRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/triagem': typeof AuthenticatedTriagemRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/calc/lista': typeof AuthenticatedCalcListaRoute
  '/_authenticated/calc/results': typeof AuthenticatedCalcResultsRoute
  '/_authenticated/calc/selecao': typeof AuthenticatedCalcSelecaoRoute
  '/_authenticated/calc/wizard': typeof AuthenticatedCalcWizardRoute
  '/_authenticated/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/_authenticated/crm/calendario': typeof AuthenticatedCrmCalendarioRoute
  '/_authenticated/crm/campos-oportunidade': typeof AuthenticatedCrmCamposOportunidadeRoute
  '/_authenticated/crm/contatos': typeof AuthenticatedCrmContatosRoute
  '/_authenticated/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/_authenticated/crm/etapas-funil': typeof AuthenticatedCrmEtapasFunilRoute
  '/_authenticated/crm/oportunidades': typeof AuthenticatedCrmOportunidadesRoute
  '/_authenticated/crm/oportunidades-arquivadas': typeof AuthenticatedCrmOportunidadesArquivadasRoute
  '/_authenticated/crm/services': typeof AuthenticatedCrmServicesRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/documents': typeof AuthenticatedSettingsDocumentsRoute
  '/_authenticated/settings/event-categories': typeof AuthenticatedSettingsEventCategoriesRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/ocr': typeof AuthenticatedSettingsOcrRoute
  '/_authenticated/peticoes/': typeof AuthenticatedPeticoesIndexRoute
  '/_authenticated/calc/relatorio/$id': typeof AuthenticatedCalcRelatorioIdRoute
  '/_authenticated/crm/etapa/$id': typeof AuthenticatedCrmEtapaIdRoute
  '/_authenticated/crm/oportunidade/$id': typeof AuthenticatedCrmOportunidadeIdRoute
  '/_authenticated/peticoes/editor/$id': typeof AuthenticatedPeticoesEditorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/dashboard'
    | '/ia-insights'
    | '/permissions'
    | '/triagem'
    | '/users'
    | '/'
    | '/calc/lista'
    | '/calc/results'
    | '/calc/selecao'
    | '/calc/wizard'
    | '/contatos/$id'
    | '/crm/calendario'
    | '/crm/campos-oportunidade'
    | '/crm/contatos'
    | '/crm/dashboard'
    | '/crm/etapas-funil'
    | '/crm/oportunidades'
    | '/crm/oportunidades-arquivadas'
    | '/crm/services'
    | '/settings/company'
    | '/settings/documents'
    | '/settings/event-categories'
    | '/settings/general'
    | '/settings/ocr'
    | '/peticoes'
    | '/calc/relatorio/$id'
    | '/crm/etapa/$id'
    | '/crm/oportunidade/$id'
    | '/peticoes/editor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/ia-insights'
    | '/permissions'
    | '/triagem'
    | '/users'
    | '/'
    | '/calc/lista'
    | '/calc/results'
    | '/calc/selecao'
    | '/calc/wizard'
    | '/contatos/$id'
    | '/crm/calendario'
    | '/crm/campos-oportunidade'
    | '/crm/contatos'
    | '/crm/dashboard'
    | '/crm/etapas-funil'
    | '/crm/oportunidades'
    | '/crm/oportunidades-arquivadas'
    | '/crm/services'
    | '/settings/company'
    | '/settings/documents'
    | '/settings/event-categories'
    | '/settings/general'
    | '/settings/ocr'
    | '/peticoes'
    | '/calc/relatorio/$id'
    | '/crm/etapa/$id'
    | '/crm/oportunidade/$id'
    | '/peticoes/editor/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/ia-insights'
    | '/_authenticated/permissions'
    | '/_authenticated/triagem'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/calc/lista'
    | '/_authenticated/calc/results'
    | '/_authenticated/calc/selecao'
    | '/_authenticated/calc/wizard'
    | '/_authenticated/contatos/$id'
    | '/_authenticated/crm/calendario'
    | '/_authenticated/crm/campos-oportunidade'
    | '/_authenticated/crm/contatos'
    | '/_authenticated/crm/dashboard'
    | '/_authenticated/crm/etapas-funil'
    | '/_authenticated/crm/oportunidades'
    | '/_authenticated/crm/oportunidades-arquivadas'
    | '/_authenticated/crm/services'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/documents'
    | '/_authenticated/settings/event-categories'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/ocr'
    | '/_authenticated/peticoes/'
    | '/_authenticated/calc/relatorio/$id'
    | '/_authenticated/crm/etapa/$id'
    | '/_authenticated/crm/oportunidade/$id'
    | '/_authenticated/peticoes/editor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/triagem': {
      id: '/_authenticated/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof AuthenticatedTriagemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ia-insights': {
      id: '/_authenticated/ia-insights'
      path: '/ia-insights'
      fullPath: '/ia-insights'
      preLoaderRoute: typeof AuthenticatedIaInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/peticoes/': {
      id: '/_authenticated/peticoes/'
      path: '/peticoes'
      fullPath: '/peticoes'
      preLoaderRoute: typeof AuthenticatedPeticoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/ocr': {
      id: '/_authenticated/settings/ocr'
      path: '/settings/ocr'
      fullPath: '/settings/ocr'
      preLoaderRoute: typeof AuthenticatedSettingsOcrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/event-categories': {
      id: '/_authenticated/settings/event-categories'
      path: '/settings/event-categories'
      fullPath: '/settings/event-categories'
      preLoaderRoute: typeof AuthenticatedSettingsEventCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/documents': {
      id: '/_authenticated/settings/documents'
      path: '/settings/documents'
      fullPath: '/settings/documents'
      preLoaderRoute: typeof AuthenticatedSettingsDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/services': {
      id: '/_authenticated/crm/services'
      path: '/crm/services'
      fullPath: '/crm/services'
      preLoaderRoute: typeof AuthenticatedCrmServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/oportunidades-arquivadas': {
      id: '/_authenticated/crm/oportunidades-arquivadas'
      path: '/crm/oportunidades-arquivadas'
      fullPath: '/crm/oportunidades-arquivadas'
      preLoaderRoute: typeof AuthenticatedCrmOportunidadesArquivadasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/oportunidades': {
      id: '/_authenticated/crm/oportunidades'
      path: '/crm/oportunidades'
      fullPath: '/crm/oportunidades'
      preLoaderRoute: typeof AuthenticatedCrmOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/etapas-funil': {
      id: '/_authenticated/crm/etapas-funil'
      path: '/crm/etapas-funil'
      fullPath: '/crm/etapas-funil'
      preLoaderRoute: typeof AuthenticatedCrmEtapasFunilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/dashboard': {
      id: '/_authenticated/crm/dashboard'
      path: '/crm/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof AuthenticatedCrmDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/contatos': {
      id: '/_authenticated/crm/contatos'
      path: '/crm/contatos'
      fullPath: '/crm/contatos'
      preLoaderRoute: typeof AuthenticatedCrmContatosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/campos-oportunidade': {
      id: '/_authenticated/crm/campos-oportunidade'
      path: '/crm/campos-oportunidade'
      fullPath: '/crm/campos-oportunidade'
      preLoaderRoute: typeof AuthenticatedCrmCamposOportunidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/calendario': {
      id: '/_authenticated/crm/calendario'
      path: '/crm/calendario'
      fullPath: '/crm/calendario'
      preLoaderRoute: typeof AuthenticatedCrmCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contatos/$id': {
      id: '/_authenticated/contatos/$id'
      path: '/contatos/$id'
      fullPath: '/contatos/$id'
      preLoaderRoute: typeof AuthenticatedContatosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calc/wizard': {
      id: '/_authenticated/calc/wizard'
      path: '/calc/wizard'
      fullPath: '/calc/wizard'
      preLoaderRoute: typeof AuthenticatedCalcWizardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calc/selecao': {
      id: '/_authenticated/calc/selecao'
      path: '/calc/selecao'
      fullPath: '/calc/selecao'
      preLoaderRoute: typeof AuthenticatedCalcSelecaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calc/results': {
      id: '/_authenticated/calc/results'
      path: '/calc/results'
      fullPath: '/calc/results'
      preLoaderRoute: typeof AuthenticatedCalcResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calc/lista': {
      id: '/_authenticated/calc/lista'
      path: '/calc/lista'
      fullPath: '/calc/lista'
      preLoaderRoute: typeof AuthenticatedCalcListaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/peticoes/editor/$id': {
      id: '/_authenticated/peticoes/editor/$id'
      path: '/peticoes/editor/$id'
      fullPath: '/peticoes/editor/$id'
      preLoaderRoute: typeof AuthenticatedPeticoesEditorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/oportunidade/$id': {
      id: '/_authenticated/crm/oportunidade/$id'
      path: '/crm/oportunidade/$id'
      fullPath: '/crm/oportunidade/$id'
      preLoaderRoute: typeof AuthenticatedCrmOportunidadeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/etapa/$id': {
      id: '/_authenticated/crm/etapa/$id'
      path: '/crm/etapa/$id'
      fullPath: '/crm/etapa/$id'
      preLoaderRoute: typeof AuthenticatedCrmEtapaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calc/relatorio/$id': {
      id: '/_authenticated/calc/relatorio/$id'
      path: '/calc/relatorio/$id'
      fullPath: '/calc/relatorio/$id'
      preLoaderRoute: typeof AuthenticatedCalcRelatorioIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIaInsightsRoute: typeof AuthenticatedIaInsightsRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedTriagemRoute: typeof AuthenticatedTriagemRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCalcListaRoute: typeof AuthenticatedCalcListaRoute
  AuthenticatedCalcResultsRoute: typeof AuthenticatedCalcResultsRoute
  AuthenticatedCalcSelecaoRoute: typeof AuthenticatedCalcSelecaoRoute
  AuthenticatedCalcWizardRoute: typeof AuthenticatedCalcWizardRoute
  AuthenticatedContatosIdRoute: typeof AuthenticatedContatosIdRoute
  AuthenticatedCrmCalendarioRoute: typeof AuthenticatedCrmCalendarioRoute
  AuthenticatedCrmCamposOportunidadeRoute: typeof AuthenticatedCrmCamposOportunidadeRoute
  AuthenticatedCrmContatosRoute: typeof AuthenticatedCrmContatosRoute
  AuthenticatedCrmDashboardRoute: typeof AuthenticatedCrmDashboardRoute
  AuthenticatedCrmEtapasFunilRoute: typeof AuthenticatedCrmEtapasFunilRoute
  AuthenticatedCrmOportunidadesRoute: typeof AuthenticatedCrmOportunidadesRoute
  AuthenticatedCrmOportunidadesArquivadasRoute: typeof AuthenticatedCrmOportunidadesArquivadasRoute
  AuthenticatedCrmServicesRoute: typeof AuthenticatedCrmServicesRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsDocumentsRoute: typeof AuthenticatedSettingsDocumentsRoute
  AuthenticatedSettingsEventCategoriesRoute: typeof AuthenticatedSettingsEventCategoriesRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsOcrRoute: typeof AuthenticatedSettingsOcrRoute
  AuthenticatedPeticoesIndexRoute: typeof AuthenticatedPeticoesIndexRoute
  AuthenticatedCalcRelatorioIdRoute: typeof AuthenticatedCalcRelatorioIdRoute
  AuthenticatedCrmEtapaIdRoute: typeof AuthenticatedCrmEtapaIdRoute
  AuthenticatedCrmOportunidadeIdRoute: typeof AuthenticatedCrmOportunidadeIdRoute
  AuthenticatedPeticoesEditorIdRoute: typeof AuthenticatedPeticoesEditorIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIaInsightsRoute: AuthenticatedIaInsightsRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedTriagemRoute: AuthenticatedTriagemRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCalcListaRoute: AuthenticatedCalcListaRoute,
  AuthenticatedCalcResultsRoute: AuthenticatedCalcResultsRoute,
  AuthenticatedCalcSelecaoRoute: AuthenticatedCalcSelecaoRoute,
  AuthenticatedCalcWizardRoute: AuthenticatedCalcWizardRoute,
  AuthenticatedContatosIdRoute: AuthenticatedContatosIdRoute,
  AuthenticatedCrmCalendarioRoute: AuthenticatedCrmCalendarioRoute,
  AuthenticatedCrmCamposOportunidadeRoute:
    AuthenticatedCrmCamposOportunidadeRoute,
  AuthenticatedCrmContatosRoute: AuthenticatedCrmContatosRoute,
  AuthenticatedCrmDashboardRoute: AuthenticatedCrmDashboardRoute,
  AuthenticatedCrmEtapasFunilRoute: AuthenticatedCrmEtapasFunilRoute,
  AuthenticatedCrmOportunidadesRoute: AuthenticatedCrmOportunidadesRoute,
  AuthenticatedCrmOportunidadesArquivadasRoute:
    AuthenticatedCrmOportunidadesArquivadasRoute,
  AuthenticatedCrmServicesRoute: AuthenticatedCrmServicesRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsDocumentsRoute: AuthenticatedSettingsDocumentsRoute,
  AuthenticatedSettingsEventCategoriesRoute:
    AuthenticatedSettingsEventCategoriesRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsOcrRoute: AuthenticatedSettingsOcrRoute,
  AuthenticatedPeticoesIndexRoute: AuthenticatedPeticoesIndexRoute,
  AuthenticatedCalcRelatorioIdRoute: AuthenticatedCalcRelatorioIdRoute,
  AuthenticatedCrmEtapaIdRoute: AuthenticatedCrmEtapaIdRoute,
  AuthenticatedCrmOportunidadeIdRoute: AuthenticatedCrmOportunidadeIdRoute,
  AuthenticatedPeticoesEditorIdRoute: AuthenticatedPeticoesEditorIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
